import type { AnnotationHistoryRecord, DatasetSummary, Episode, SegmentAnnotation } from "./types";

export const datasetSummary: DatasetSummary = {
  datasetId: "sample-xvla-soft-fold",
  name: "sample-xvla-soft-fold",
  uri: "sample://xvla-soft-fold",
  status: "sample",
  episodeCount: 3,
  frameCount: 576,
  fps: 20,
  cameraNames: ["cam_high", "cam_left_wrist", "cam_right_wrist"],
  cameraInfo: null,
  reviewedCount: 2,
  acceptedCount: 2,
  rejectedCount: 0,
  storageLayout: "published_hf",
  primaryTrainingTable: "episodes.lance",
  annotationStorage: "local_overlay",
  sourceSessionCount: null,
  datasetIdSource: "uri",
  actionSemantics: null
};

export const episodes: Episode[] = [
  {
    datasetId: datasetSummary.datasetId,
    episodeIndex: 0,
    taskIndex: 3,
    length: 180,
    successLabel: true,
    qualityScore: 0.72,
    reviewStatus: "accepted",
    caption: "Soft cloth folding trajectory",
    failureReason: "",
    hasVlmLabel: false,
    hasHumanLabel: false,
    split: "train",
    fps: 20,
    cameraNames: datasetSummary.cameraNames,
    languageInstruction: null,
    taskSegments: [],
    dirtyAnnotationCount: 0
  },
  {
    datasetId: datasetSummary.datasetId,
    episodeIndex: 1,
    taskIndex: 3,
    length: 192,
    successLabel: false,
    qualityScore: 0.77,
    reviewStatus: "pending",
    caption: "Failed fold with cloth slip",
    failureReason: "cloth slip",
    hasVlmLabel: true,
    hasHumanLabel: false,
    split: "train",
    fps: 20,
    cameraNames: datasetSummary.cameraNames,
    languageInstruction: null,
    taskSegments: [],
    dirtyAnnotationCount: 0
  },
  {
    datasetId: datasetSummary.datasetId,
    episodeIndex: 2,
    taskIndex: 3,
    length: 204,
    successLabel: true,
    qualityScore: 0.82,
    reviewStatus: "accepted",
    caption: "Clean edge grasp and fold",
    failureReason: "",
    hasVlmLabel: true,
    hasHumanLabel: true,
    split: "val",
    fps: 20,
    cameraNames: datasetSummary.cameraNames,
    languageInstruction: null,
    taskSegments: [],
    dirtyAnnotationCount: 0
  }
];

export const annotations: SegmentAnnotation[] = [
  {
    id: "seg-approach",
    datasetId: datasetSummary.datasetId,
    episodeIndex: 0,
    startFrame: 0,
    endFrame: 38,
    labelType: "phase",
    labelValue: "approach",
    source: "human",
    confidence: 1,
    reviewStatus: "accepted",
    metadata: {},
    createdBy: "local",
    updatedBy: "local",
    assignedTo: null,
    revision: 1,
    deletedAt: null,
    lockOwner: null,
    lockExpiresAt: null,
    appliedExportId: null
  },
  {
    id: "seg-grasp",
    datasetId: datasetSummary.datasetId,
    episodeIndex: 0,
    startFrame: 39,
    endFrame: 88,
    labelType: "phase",
    labelValue: "cloth_edge_grasp",
    source: "vlm",
    confidence: 0.82,
    reviewStatus: "pending",
    metadata: {},
    createdBy: "vlm",
    updatedBy: "vlm",
    assignedTo: "local",
    revision: 1,
    deletedAt: null,
    lockOwner: null,
    lockExpiresAt: null,
    appliedExportId: null
  },
  {
    id: "seg-fold",
    datasetId: datasetSummary.datasetId,
    episodeIndex: 0,
    startFrame: 89,
    endFrame: 156,
    labelType: "phase",
    labelValue: "fold",
    source: "human",
    confidence: 1,
    reviewStatus: "accepted",
    metadata: {},
    createdBy: "local",
    updatedBy: "local",
    assignedTo: null,
    revision: 1,
    deletedAt: null,
    lockOwner: null,
    lockExpiresAt: null,
    appliedExportId: null
  },
  {
    id: "seg-release",
    datasetId: datasetSummary.datasetId,
    episodeIndex: 0,
    startFrame: 157,
    endFrame: 180,
    labelType: "phase",
    labelValue: "release",
    source: "heuristic",
    confidence: 0.64,
    reviewStatus: "pending",
    metadata: {},
    createdBy: "heuristic",
    updatedBy: "heuristic",
    assignedTo: "local",
    revision: 1,
    deletedAt: null,
    lockOwner: null,
    lockExpiresAt: null,
    appliedExportId: null
  }
];

export const annotationHistory: AnnotationHistoryRecord[] = [
  {
    eventId: "hist-approach-create",
    datasetId: datasetSummary.datasetId,
    annotationId: "seg-approach",
    episodeIndex: 0,
    action: "create",
    actor: "local",
    before: null,
    after: {
      start_frame: 0,
      end_frame: 38,
      label_type: "phase",
      label_value: "approach",
      review_status: "accepted"
    },
    createdAt: "2026-05-05T00:00:00.000Z"
  },
  {
    eventId: "hist-grasp-update",
    datasetId: datasetSummary.datasetId,
    annotationId: "seg-grasp",
    episodeIndex: 0,
    action: "update",
    actor: "local",
    before: {
      start_frame: 39,
      end_frame: 88,
      label_type: "phase",
      label_value: "grasp",
      review_status: "pending"
    },
    after: {
      start_frame: 39,
      end_frame: 88,
      label_type: "phase",
      label_value: "cloth_edge_grasp",
      review_status: "pending"
    },
    createdAt: "2026-05-05T00:01:00.000Z"
  }
];
