/**
 * Generated from packages/robot_schema/humanoid_skills.json.
 * Do not edit this file directly; run:
 *   python3 scripts/generate_skill_vocabulary_ts.py
 */

export type HumanoidSkill = {
  /** Numeric skill id (0-9), used for keyboard shortcuts */
  id: number;
  /** Machine-readable name, stored as label_value */
  name: string;
  /** Human-readable display label */
  label: string;
  /** Unique color for timeline / list badges */
  color: string;
  startCondition: string | null;
  endCondition: string | null;
  missionSection: string | null;
};

export const HUMANOID_SKILLS: readonly HumanoidSkill[] = [
  {
    id: 0,
    name: "approach",
    label: "Approach",
    color: "#4A90D9",
    startCondition: "arbitrary position",
    endCondition: "near target object",
    missionSection: "A/C/D"
  },
  {
    id: 1,
    name: "grasp_part",
    label: "Grasp Part",
    color: "#50C878",
    startCondition: "near target part",
    endCondition: "part grasped",
    missionSection: "A"
  },
  {
    id: 2,
    name: "grasp_bolt",
    label: "Grasp Bolt",
    color: "#8B5CF6",
    startCondition: "near bolt",
    endCondition: "bolt grasped",
    missionSection: "B"
  },
  {
    id: 3,
    name: "insert_bolt",
    label: "Insert Bolt",
    color: "#F59E0B",
    startCondition: "bolt grasped",
    endCondition: "bolt inserted",
    missionSection: "B"
  },
  {
    id: 4,
    name: "place",
    label: "Place",
    color: "#EF4444",
    startCondition: "object grasped",
    endCondition: "object placed",
    missionSection: "A/C/D"
  },
  {
    id: 5,
    name: "push_button",
    label: "Push Button",
    color: "#EC4899",
    startCondition: "near button",
    endCondition: "button pressed",
    missionSection: "C"
  },
  {
    id: 6,
    name: "grasp_drill",
    label: "Grasp Drill",
    color: "#14B8A6",
    startCondition: "near drill",
    endCondition: "drill grasped",
    missionSection: "C"
  },
  {
    id: 7,
    name: "drill_trigger",
    label: "Drill Trigger",
    color: "#F97316",
    startCondition: "drill positioned",
    endCondition: "trigger pulled",
    missionSection: "C"
  },
  {
    id: 8,
    name: "bimanual_grasp",
    label: "Bimanual Grasp",
    color: "#6366F1",
    startCondition: "both hands near object",
    endCondition: "object controlled by both hands",
    missionSection: "D"
  },
  {
    id: 9,
    name: "insert_tire",
    label: "Insert Tire",
    color: "#0EA5E9",
    startCondition: "tire grasped",
    endCondition: "tire inserted",
    missionSection: "D"
  },
] as const;

/** Segment label_type used for all skill clips */
export const SKILL_LABEL_TYPE = "skill" as const;

/** Look up a skill by numeric id */
export function skillById(id: number): HumanoidSkill | undefined {
  return HUMANOID_SKILLS.find((skill) => skill.id === id);
}

/** Look up a skill by name (label_value in DB) */
export function skillByName(name: string): HumanoidSkill | undefined {
  const canonical = HUMANOID_SKILLS.find((skill) => skill.name === name);
  if (canonical) return canonical;
  // Fall back to user-defined custom skills (localStorage). These are
  // exploratory only — exporting still rejects them per the canonical
  // contract, but they participate fully in the in-app UI.
  if (typeof window === "undefined") return undefined;
  try {
    const raw = window.localStorage.getItem("rds.customSkills");
    if (!raw) return undefined;
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return undefined;
    const custom = parsed.find(
      (item: { name?: string }) =>
        typeof item?.name === "string" && item.name === name
    ) as { name: string; label: string; color: string } | undefined;
    if (!custom) return undefined;
    return {
      id: -1,
      name: custom.name,
      label: custom.label,
      color: custom.color,
      startCondition: null,
      endCondition: null,
      missionSection: null
    };
  } catch {
    return undefined;
  }
}
