from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages" / "robot_schema" / "humanoid_skills.json"
TARGET = ROOT / "apps" / "web" / "lib" / "skill-vocabulary.ts"


def _camel_optional(value: object) -> str:
    if value is None:
        return "null"
    return json.dumps(str(value), ensure_ascii=False)


def main() -> None:
    skills = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        "/**",
        " * Generated from packages/robot_schema/humanoid_skills.json.",
        " * Do not edit this file directly; run:",
        " *   python3 scripts/generate_skill_vocabulary_ts.py",
        " */",
        "",
        "export type HumanoidSkill = {",
        "  /** Numeric skill id (0-9), used for keyboard shortcuts */",
        "  id: number;",
        "  /** Machine-readable name, stored as label_value */",
        "  name: string;",
        "  /** Human-readable display label */",
        "  label: string;",
        "  /** Unique color for timeline / list badges */",
        "  color: string;",
        "  startCondition: string | null;",
        "  endCondition: string | null;",
        "  missionSection: string | null;",
        "};",
        "",
        "export const HUMANOID_SKILLS: readonly HumanoidSkill[] = [",
    ]
    for skill in skills:
        lines.extend(
            [
                "  {",
                f"    id: {int(skill['skill_id'])},",
                f"    name: {json.dumps(skill['skill_name'])},",
                f"    label: {json.dumps(skill['display_label'])},",
                f"    color: {json.dumps(skill.get('color') or '#64748B')},",
                f"    startCondition: {_camel_optional(skill.get('start_condition'))},",
                f"    endCondition: {_camel_optional(skill.get('end_condition'))},",
                f"    missionSection: {_camel_optional(skill.get('mission_section'))}",
                "  },",
            ]
        )
    lines.extend(
        [
            "] as const;",
            "",
            "/** Segment label_type used for all skill clips */",
            'export const SKILL_LABEL_TYPE = "skill" as const;',
            "",
            "/** Look up a skill by numeric id */",
            "export function skillById(id: number): HumanoidSkill | undefined {",
            "  return HUMANOID_SKILLS.find((skill) => skill.id === id);",
            "}",
            "",
            "/** Look up a skill by name (label_value in DB) */",
            "export function skillByName(name: string): HumanoidSkill | undefined {",
            "  return HUMANOID_SKILLS.find((skill) => skill.name === name);",
            "}",
            "",
        ]
    )
    TARGET.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
